USE [master];
GO

CREATE DATABASE [MTLEdata] COLLATE Thai_CI_AS;
GO

ALTER DATABASE [MTLEdata] MODIFY FILE
(NAME = N'MTLEdata' , SIZE = 5MB , MAXSIZE = 1GB, FILEGROWTH = 1MB);
GO

ALTER DATABASE [MTLEdata] MODIFY FILE
(NAME = N'MTLEdata_log' , SIZE = 2MB , MAXSIZE = 512MB , FILEGROWTH = 10%);
GO
